os: linux
language: ruby
dist: focal
#sudo: true
services:
- docker
install: skip
script: true
before_deploy:
  - git remote -v            # Check the remote URL configuration
  - git status               # View the state of the repository
  - git log -3               # Show the last 3 commits to ensure the correct commit is being pushed
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  dpl_version: 1.10.16
  on:
    branch: main
#  env:
#    global:
#      secure: vuZhXpRw0ia7aKwB/rwU5n8dItvboSkOi1AyrGEQIJaZP6TlP+NBZgT/f8HxtCG9keCwswnufisBXxe6dpvH7iPdNiYf9IEgUnzp4yXkms+OWCReu3blLWMQGZ8XT10EE0iEJ0Qi8VMIY5L5vGkbu+kTE/f7obU13zAUWqN9ZVJHl/oRCJMC+dS3uRVmBM6145lLYhsnifLN06gA78UKf7lb/dw3szsWwF1FdD9xCuq3Dce+uqUYasJtiLajwVH6B6qOI1YoIkC/r/wFt2EL4DXRxPQSI53yXc5cUZ4BywYpjKcskLSXSwBhI0tEGzTzTZPvzDxNWSMQ6OCVbdLv9j5xnfyfJQbB50ndG0YFfFyLXzGT/bSN5ghnKOA80O5boI1xUQKP47kOOLz/IX6eNayHz/YGm6ia/Dj6QuHxtOFsxVokUHvQeZtRpjCsq6E5RY5qjKueVMjRSTQRgPdWKT9A5XSAud3fiRQg93dZfQsx0NAM1WIhAOI8584eGmLe3OnwUKmVkUDPEVZkpimkiQnaDKz28iRecB8hEBxfa+SGggumvOMuDIWnZrPheZBVKiqi7pXmB1SyvOt/bvlZNNsDRz/h0VrZk4e0NTMgudAFPPquZuZVuIq+jo5sCSbQk3Pp3ek0Jri02PltPDS+Ae+/QENaW4n3dv4rLIuuocw=

#second test
