os: linux
language: ruby
dist: focal
group: previous
#sudo: true
services:
- docker
install: skip
script: true
before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install logger
  - gem install faraday -v 1.8.0
#before_deploy:
#  - git remote -v            # Check the remote URL configuration
#  - git status               # View the state of the repository
#  - git log -3               # Show the last 3 commits to ensure the correct commit is being pushed
deploy:
  - provider: pages
    skip_cleanup: true
#    overwrite: true
#    draft: true
    github-token: $GITHUB_TOKEN
    edge: true
    dpl_version: 2.0.3.beta.4
#  target_branch: master 
    'on':
      branch: main
