os: linux
language: ruby
dist: xenial
sudo: true
services:
  - docker
install: skip
script: true
#before_deploy:
#  - yes | gem update --system --force
#  - gem install bundler
#  - gem install uri
#  - gem install logger
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  dpl_version: 1.10.16
  on:
    branch: main


#deploy:
#  - provider: pages
#    strategy: git
#  edge:
#    branch: v2.0.5
#    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#      on:
#    branch: main
