os: linux
#jdk: openjdk11
#language: java
dist: jammy
#services:
#- docker


script: true
#before_script:
#- command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
#- git config --global user.name "travis"
#- git config --global user.email "travis@users.noreply.github.com"
#- git remote set-url origin https://$GITHUB_TOKEN@github.com/erika-kuntar/ghpagessept23.git

#before_deploy:
#- git config --global credential.helper store
#- git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
#- git remote -v
#- git fetch -v
#- git push origin HEAD:main
#- git push --dry-run --verbose https://erika-kuntar:$GITHUB_TOKEN@github.com/erika-kuntar/ghpagessept23.git HEAD:main
#before_script:

# - git remote set-url origin https://$GITHUB_TOKEN@github.com/erika-kuntar/ghpagessept23.git
#- git status
#- git clone https://${GITHUB_TOKEN}@github.com/erika-kuntar/ghpagessept23.git
#- git remote add origin-pages https://${GH_TOKEN}@github.com/erika-kuntar/ghpagessept23.git > /dev/null 2>&1
#- git checkout -b gh-pages
#- git add .
#- git commit --message "test"
#- git push --set-upstream origin-pages gh-pages 
#deploy:
#- provider: pages
#  verbose: true
#  github-token: "$GITHUB_TOKEN"
#  edge: true
#  dpl_version: 2.0.5.3
#  on:
#    branch: main
#before_install:
#- gem install bundler



before_install:
#- gem update --system
#- yes | gem update --system --force
#- gem install bundler
#- gem install uri
#- gem install bundler -v 2.5.16 
# gem install logger -v 1.6.4
#- gem install faraday -v 2.12.0
deploy: 
- provider: s3
  access_key_id: "$SECRET_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
#  skip_cleanup: true
  edge: true
  dpl_version: 2.0.5.3
  bucket: "$BUCKET"
  'on':
    branch:
    - mar24


#testing
