os: linux
arch:
  - arm64
language: python
python:
  - "3.7"
install: skip
script: true
before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install logger
deploy:
  provider: pages
  edge:
    branch: v2.0.5
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: main
